cp -i ./seacas/applications/blot/symbol.f tmp
cp -i ./seacas/applications/blot/ugrcol.f tmp
cp -i ./seacas/applications/fastq/add1cn.f tmp
cp -i ./seacas/applications/fastq/add2cn.f tmp
cp -i ./seacas/applications/fastq/add2el.f tmp
cp -i ./seacas/applications/fastq/add2nd.f tmp
cp -i ./seacas/applications/fastq/add3nd.f tmp
cp -i ./seacas/applications/fastq/addkxl.f tmp
cp -i ./seacas/applications/fastq/addlxn.f tmp
cp -i ./seacas/applications/fastq/addnod.f tmp
cp -i ./seacas/applications/fastq/addrow.f tmp
cp -i ./seacas/applications/fastq/addtuk.f tmp
cp -i ./seacas/applications/fastq/addwdg.f tmp
cp -i ./seacas/applications/fastq/adjrow.f tmp
cp -i ./seacas/applications/fastq/adjtri.f tmp
cp -i ./seacas/applications/fastq/b4bad.f tmp
cp -i ./seacas/applications/fastq/bcross.f tmp
cp -i ./seacas/applications/fastq/bpinch.f tmp
cp -i ./seacas/applications/fastq/cgi/vdicps.f tmp
cp -i ./seacas/applications/fastq/ch3to4.f tmp
cp -i ./seacas/applications/fastq/close2.f tmp
cp -i ./seacas/applications/fastq/close4.f tmp
cp -i ./seacas/applications/fastq/close6.f tmp
cp -i ./seacas/applications/fastq/cntcrn.f tmp
cp -i ./seacas/applications/fastq/colaps.f tmp
cp -i ./seacas/applications/fastq/comsrt.f tmp
cp -i ./seacas/applications/fastq/connod.f tmp
cp -i ./seacas/applications/fastq/d2node.f tmp
cp -i ./seacas/applications/fastq/delem.f tmp
cp -i ./seacas/applications/fastq/dellxn.f tmp
cp -i ./seacas/applications/fastq/dlpara.f tmp
cp -i ./seacas/applications/fastq/eqlang.f tmp
cp -i ./seacas/applications/fastq/extnd1.f tmp
cp -i ./seacas/applications/fastq/extnd3.f tmp
cp -i ./seacas/applications/fastq/extnd5.f tmp
cp -i ./seacas/applications/fastq/filsmo.f tmp
cp -i ./seacas/applications/fastq/fixlxn.f tmp
cp -i ./seacas/applications/fastq/flmnmx.f tmp
cp -i ./seacas/applications/fastq/fndlnk.f tmp
cp -i ./seacas/applications/fastq/getang.f tmp
cp -i ./seacas/applications/fastq/getcrn.f tmp
cp -i ./seacas/applications/fastq/getdum.f tmp
cp -i ./seacas/applications/fastq/getfrm.f tmp
cp -i ./seacas/applications/fastq/getime.f tmp
cp -i ./seacas/applications/fastq/getlxn.f tmp
cp -i ./seacas/applications/fastq/getrow.f tmp
cp -i ./seacas/applications/fastq/getsiz.f tmp
cp -i ./seacas/applications/fastq/gkxn.f tmp
cp -i ./seacas/applications/fastq/gnxka.f tmp
cp -i ./seacas/applications/fastq/intsct.f tmp
cp -i ./seacas/applications/fastq/invert.f tmp
cp -i ./seacas/applications/fastq/invmap.f tmp
cp -i ./seacas/applications/fastq/keep3.f tmp
cp -i ./seacas/applications/fastq/lcolor.f tmp
cp -i ./seacas/applications/fastq/longel.f tmp
cp -i ./seacas/applications/fastq/lupang.f tmp
cp -i ./seacas/applications/fastq/marksm.f tmp
cp -i ./seacas/applications/fastq/match2.f tmp
cp -i ./seacas/applications/fastq/mesage.f tmp
cp -i ./seacas/applications/fastq/mnorm.f tmp
cp -i ./seacas/applications/fastq/ndstat.f tmp
cp -i ./seacas/applications/fastq/node12.f tmp
cp -i ./seacas/applications/fastq/nsplit.f tmp
cp -i ./seacas/applications/fastq/nxkord.f tmp
cp -i ./seacas/applications/fastq/pcross.f tmp
cp -i ./seacas/applications/fastq/periml.f tmp
cp -i ./seacas/applications/fastq/pinch.f tmp
cp -i ./seacas/applications/fastq/putlxn.f tmp
cp -i ./seacas/applications/fastq/qual2n.f tmp
cp -i ./seacas/applications/fastq/qual3.f tmp
cp -i ./seacas/applications/fastq/qual4.f tmp
cp -i ./seacas/applications/fastq/ringbl.f tmp
cp -i ./seacas/applications/fastq/rowsmo.f tmp
cp -i ./seacas/applications/fastq/rplotl.f tmp
cp -i ./seacas/applications/fastq/setcir.f tmp
cp -i ./seacas/applications/fastq/setlop.f tmp
cp -i ./seacas/applications/fastq/setn02.f tmp
cp -i ./seacas/applications/fastq/sew2.f tmp
cp -i ./seacas/applications/fastq/sflush.f tmp
cp -i ./seacas/applications/fastq/snapit.f tmp
cp -i ./seacas/applications/fastq/spaced.f tmp
cp -i ./seacas/applications/fastq/tridel.f tmp
cp -i ./seacas/applications/fastq/trifix.f tmp
cp -i ./seacas/applications/fastq/tuck.f tmp
cp -i ./seacas/applications/fastq/undelm.f tmp
cp -i ./seacas/applications/fastq/vinter.f tmp
cp -i ./seacas/applications/fastq/wedge.f tmp
cp -i ./seacas/libraries/plt/chric.f tmp
cp -i ./seacas/libraries/plt/chrtrm.f tmp
cp -i ./seacas/libraries/plt/cpudac.f tmp
cp -i ./seacas/libraries/plt/mpd2vc.f tmp
cp -i ./seacas/libraries/plt/mpmul2.f tmp
cp -i ./seacas/libraries/plt/mpmul4.f tmp
cp -i ./seacas/libraries/plt/mport2.f tmp
cp -i ./seacas/libraries/plt/mpview.f tmp
cp -i ./seacas/libraries/plt/mxmult.f tmp
cp -i ./seacas/libraries/plt/mxzero.f tmp
cp -i ./seacas/libraries/plt/pltbel.f tmp
cp -i ./seacas/libraries/plt/pltbgn.f tmp
cp -i ./seacas/libraries/plt/pltcv2.f tmp
cp -i ./seacas/libraries/plt/pltdrw.f tmp
cp -i ./seacas/libraries/plt/pltflu.f tmp
cp -i ./seacas/libraries/plt/pltfrm.f tmp
cp -i ./seacas/libraries/plt/pltlig.f tmp
cp -i ./seacas/libraries/plt/pltmov.f tmp
cp -i ./seacas/libraries/plt/pltp2d.f tmp
cp -i ./seacas/libraries/plt/pltrim.f tmp
cp -i ./seacas/libraries/plt/pltrsd.f tmp
cp -i ./seacas/libraries/plt/pltstd.f tmp
cp -i ./seacas/libraries/plt/pltvcm.f tmp
cp -i ./seacas/libraries/plt/pltvwp.f tmp
cp -i ./seacas/libraries/plt/pltvwv.f tmp
cp -i ./seacas/libraries/plt/pltxth.f tmp
cp -i ./seacas/libraries/plt/siorpt.f tmp
