f2c -C++ add1cn.f
f2c -C++ add2cn.f
f2c -C++ add2el.f
f2c -C++ add2nd.f
f2c -C++ add3nd.f
f2c -C++ addjut.f
f2c -C++ addkxl.f
f2c -C++ addlxn.f
f2c -C++ addnod.f
f2c -C++ addrow.f
f2c -C++ addsnp.f
f2c -C++ addtuk.f
f2c -C++ addwdg.f
f2c -C++ addwt.f
f2c -C++ adjmsh.f
f2c -C++ adjrow.f
f2c -C++ adjtri.f
f2c -C++ amxbm.f
f2c -C++ apalib.f
f2c -C++ apalsm.f
f2c -C++ arcpar.f
f2c -C++ arcy.f
f2c -C++ arelax.f
f2c -C++ b4bad.f
f2c -C++ bcross.f
f2c -C++ bfnode.f
f2c -C++ bmschm.f
f2c -C++ boxit.f
f2c -C++ bpinch.f
f2c -C++ bubble.f
f2c -C++ casmo.f
f2c -C++ cclock.f
f2c -C++ ch3to4.f
f2c -C++ chcond.f
f2c -C++ chkhol.f
f2c -C++ chkkxl.f
f2c -C++ chkrgn.f
f2c -C++ chkwt.f
f2c -C++ ciapal.f
f2c -C++ close2.f
f2c -C++ close4.f
f2c -C++ close6.f
f2c -C++ closeg.f
f2c -C++ closel.f
f2c -C++ closep.f
f2c -C++ cntcrn.f
f2c -C++ colaps.f
f2c -C++ comsrt.f
f2c -C++ condno.f
f2c -C++ connod.f
f2c -C++ cornp.f
f2c -C++ cpubrk.f
f2c -C++ crcsiz.f
f2c -C++ cross.f
f2c -C++ csmang.f
f2c -C++ d2grid.f
f2c -C++ d2node.f
f2c -C++ dataok.f
f2c -C++ delem.f
f2c -C++ delfsq.f
f2c -C++ delhol.f
f2c -C++ dellxn.f
f2c -C++ disclm.f
f2c -C++ disctp.f
f2c -C++ dline.f
f2c -C++ dlpara.f
f2c -C++ dmess.f
f2c -C++ dpread.f
f2c -C++ dread.f
f2c -C++ dstort.f
f2c -C++ elaray.f
f2c -C++ elipse.f
f2c -C++ elpspr.f
f2c -C++ endtan.f
f2c -C++ eqlang.f
f2c -C++ erasec.f
f2c -C++ esolve.f
f2c -C++ etheta.f
f2c -C++ excorn.f
f2c -C++ exdsct.f
f2c -C++ exisop.f
f2c -C++ exside.f
f2c -C++ extnd1.f
f2c -C++ extnd3.f
f2c -C++ extnd5.f
f2c -C++ fastq.f
f2c -C++ fexit.f
f2c -C++ filsmo.f
f2c -C++ fixlxn.f
f2c -C++ fixsub.f
f2c -C++ flagd.f
f2c -C++ flagk.f
f2c -C++ flmnmx.f
f2c -C++ fndlin.f
f2c -C++ fndlnk.f
f2c -C++ fq_check.f
f2c -C++ fq_dbpini.f
f2c -C++ fq_help.f
f2c -C++ fq_indexi.f
f2c -C++ fq_minmax.f
f2c -C++ fq_rotate.f
f2c -C++ fxnuid.f
f2c -C++ gdata.f
f2c -C++ getang.f
f2c -C++ getcrn.f
f2c -C++ getdum.f
f2c -C++ getext.f
f2c -C++ getfrm.f
f2c -C++ geti12.f
f2c -C++ geti1r.f
f2c -C++ getime.f
f2c -C++ getkxn.f
f2c -C++ getlxn.f
f2c -C++ getm1.f
f2c -C++ getm3.f
f2c -C++ getm5.f
f2c -C++ getnxn.f
f2c -C++ getplp.f
f2c -C++ getr12.f
f2c -C++ getrow.f
f2c -C++ getsbc.f
f2c -C++ getsiz.f
f2c -C++ gettrn.f
f2c -C++ getwt.f
f2c -C++ gkxn.f
f2c -C++ gmesh.f
f2c -C++ gnlist.f
f2c -C++ gnxka.f
f2c -C++ gtxdum.f
f2c -C++ inattr.f
f2c -C++ inbody.f
f2c -C++ inboun.f
f2c -C++ inbrst.f
f2c -C++ indx.f
f2c -C++ infact.f
f2c -C++ ingrid.f
f2c -C++ ingrpn.f
f2c -C++ inhole.f
f2c -C++ inintr.f
f2c -C++ initdg.f
f2c -C++ inline.f
f2c -C++ innerh.f
f2c -C++ inpoin.f
f2c -C++ inqstr.f
f2c -C++ inqtru.f
f2c -C++ inregn.f
f2c -C++ inrenm.f
f2c -C++ inschm.f
f2c -C++ inside.f
f2c -C++ intrup.f
f2c -C++ intsct.f
f2c -C++ invert.f
f2c -C++ invmap.f
f2c -C++ ioccur.f
f2c -C++ irever.f
f2c -C++ isolap.f
f2c -C++ jumplp.f
f2c -C++ keep34.f
f2c -C++ keep3.f
f2c -C++ keyin.f
f2c -C++ kxnadd.f
f2c -C++ l2smo.f
f2c -C++ labove.f
f2c -C++ lcolor.f
f2c -C++ linepr.f
f2c -C++ linkbc.f
f2c -C++ linken.f
f2c -C++ linlen.f
f2c -C++ listbf.f
f2c -C++ list.f
f2c -C++ llist.f
f2c -C++ longel.f
f2c -C++ lowfnd.f
f2c -C++ lpntin.f
f2c -C++ lswap.f
f2c -C++ ltadd.f
f2c -C++ ltnew.f
f2c -C++ ltsort.f
f2c -C++ lupang.f
f2c -C++ mak2el.f
f2c -C++ marksm.f
f2c -C++ match2.f
f2c -C++ matchk.f
f2c -C++ mesage.f
f2c -C++ mesh.f
f2c -C++ midnod.f
f2c -C++ mixvar.f
f2c -C++ mkused.f
f2c -C++ mmschm.f
f2c -C++ mnmxk.f
f2c -C++ mnorm.f
f2c -C++ ncklce.f
f2c -C++ ndstat.f
f2c -C++ nickc.f
f2c -C++ nicks.f
f2c -C++ node12.f
f2c -C++ nodord.f
f2c -C++ normnd.f
f2c -C++ nps.f
f2c -C++ nsplit.f
f2c -C++ nxkbdy.f
f2c -C++ nxkord.f
f2c -C++ parc.f
f2c -C++ paving.f
f2c -C++ pcross.f
f2c -C++ pdata.f
f2c -C++ perim.f
f2c -C++ periml.f
f2c -C++ pickm1.f
f2c -C++ pickm3.f
f2c -C++ pickm5.f
f2c -C++ picktr.f
f2c -C++ pinch.f
f2c -C++ pline.f
f2c -C++ plotl.f
f2c -C++ pmschm.f
f2c -C++ pschem.f
f2c -C++ putcrs.f
f2c -C++ putlxn.f
f2c -C++ qaaval.f
f2c -C++ qmesh.f
f2c -C++ qual2.f
f2c -C++ qual2n.f
f2c -C++ qual3.f
f2c -C++ qual4.f
f2c -C++ rdfsq.f
f2c -C++ rdmesh.f
f2c -C++ regext.f
f2c -C++ renum.f
f2c -C++ repsmo.f
f2c -C++ resta.f
f2c -C++ restry.f
f2c -C++ revers.f
f2c -C++ rgdstr.f
f2c -C++ rgnsch.f
f2c -C++ ringbl.f
f2c -C++ rmesh.f
f2c -C++ rowsmo.f
f2c -C++ rplotl.f
f2c -C++ savreg.f
f2c -C++ setaxs.f
f2c -C++ setcir.f
f2c -C++ setlop.f
f2c -C++ setn02.f
f2c -C++ sew2.f
f2c -C++ sflush.f
f2c -C++ shrunk.f
f2c -C++ sidep.f
f2c -C++ skinit.f
f2c -C++ skprnt.f
f2c -C++ smogs.f
f2c -C++ snapit.f
f2c -C++ snappt.f
f2c -C++ snapxy.f
f2c -C++ snpin1.f
f2c -C++ solve.f
f2c -C++ sort.f
f2c -C++ sortia.f
f2c -C++ sortst.f
f2c -C++ spaced.f
f2c -C++ spawn.f
f2c -C++ spiral.f
f2c -C++ spring.f
f2c -C++ squash.f
f2c -C++ srtnbc.f
f2c -C++ srtsbc.f
f2c -C++ strait.f
f2c -C++ strcut.f
f2c -C++ strlng.f
f2c -C++ strsiz.f
f2c -C++ subpen.f
f2c -C++ subtri.f
f2c -C++ subtrn.f
f2c -C++ tabint.f
f2c -C++ tablet.f
f2c -C++ tmschm.f
f2c -C++ tridel.f
f2c -C++ trifix.f
f2c -C++ tuck.f
f2c -C++ umschm.f
f2c -C++ undelm.f
f2c -C++ unisnp.f
f2c -C++ vinter.f
f2c -C++ wedge.f
f2c -C++ wrabqs.f
f2c -C++ wrex2.f
f2c -C++ wrfsq.f
f2c -C++ wrgens.f
f2c -C++ wrjerr.f
f2c -C++ wrnast.f
f2c -C++ zhole.f
f2c -C++ zoomlt.f
