f2c -C++ add1cn.f
f2c -C++ add2cn.f
f2c -C++ add2el.f
f2c -C++ add2nd.f
f2c -C++ add3nd.f
f2c -C++ addkxl.f
f2c -C++ addlxn.f
f2c -C++ addnod.f
f2c -C++ addrow.f
f2c -C++ addtuk.f
f2c -C++ addwdg.f
f2c -C++ adjrow.f
f2c -C++ adjtri.f
f2c -C++ b4bad.f
f2c -C++ bcross.f
f2c -C++ bpinch.f
f2c -C++ ch3to4.f
f2c -C++ chric.f
f2c -C++ chrtrm.f
f2c -C++ close2.f
f2c -C++ close4.f
f2c -C++ close6.f
f2c -C++ cntcrn.f
f2c -C++ colaps.f
f2c -C++ comsrt.f
f2c -C++ connod.f
f2c -C++ cpudac.f
f2c -C++ d2node.f
f2c -C++ delem.f
f2c -C++ dellxn.f
f2c -C++ dlpara.f
f2c -C++ eqlang.f
f2c -C++ extnd1.f
f2c -C++ extnd3.f
f2c -C++ extnd5.f
f2c -C++ filsmo.f
f2c -C++ fixlxn.f
f2c -C++ flmnmx.f
f2c -C++ fndlnk.f
f2c -C++ getang.f
f2c -C++ getcrn.f
f2c -C++ getdum.f
f2c -C++ getfrm.f
f2c -C++ getime.f
f2c -C++ getlxn.f
f2c -C++ getrow.f
f2c -C++ getsiz.f
f2c -C++ gkxn.f
f2c -C++ gnxka.f
f2c -C++ intsct.f
f2c -C++ invert.f
f2c -C++ invmap.f
f2c -C++ keep3.f
f2c -C++ lcolor.f
f2c -C++ longel.f
f2c -C++ lupang.f
f2c -C++ marksm.f
f2c -C++ match2.f
f2c -C++ mesage.f
f2c -C++ mnorm.f
f2c -C++ mpd2vc.f
f2c -C++ mpmul2.f
f2c -C++ mpmul4.f
f2c -C++ mport2.f
f2c -C++ mpview.f
f2c -C++ mxmult.f
f2c -C++ mxzero.f
f2c -C++ ndstat.f
f2c -C++ node12.f
f2c -C++ nsplit.f
f2c -C++ nxkord.f
f2c -C++ pcross.f
f2c -C++ periml.f
f2c -C++ pinch.f
f2c -C++ pltbel.f
f2c -C++ pltbgn.f
f2c -C++ pltcv2.f
f2c -C++ pltdrw.f
f2c -C++ pltflu.f
f2c -C++ pltfrm.f
f2c -C++ pltlig.f
f2c -C++ pltmov.f
f2c -C++ pltp2d.f
f2c -C++ pltrim.f
f2c -C++ pltrsd.f
f2c -C++ pltstd.f
f2c -C++ pltvcm.f
f2c -C++ pltvwp.f
f2c -C++ pltvwv.f
f2c -C++ pltxth.f
f2c -C++ putlxn.f
f2c -C++ qual2n.f
f2c -C++ qual3.f
f2c -C++ qual4.f
f2c -C++ ringbl.f
f2c -C++ rowsmo.f
f2c -C++ rplotl.f
f2c -C++ setcir.f
f2c -C++ setlop.f
f2c -C++ setn02.f
f2c -C++ sew2.f
f2c -C++ sflush.f
f2c -C++ siorpt.f
f2c -C++ snapit.f
f2c -C++ spaced.f
f2c -C++ symbol.f
f2c -C++ tridel.f
f2c -C++ trifix.f
f2c -C++ tuck.f
f2c -C++ ugrcol.f
f2c -C++ undelm.f
f2c -C++ vdicps.f
f2c -C++ vinter.f
f2c -C++ wedge.f
